print("===================   XXXXXXXXXXXXXXXXXXXXXXXXXXXX   ======================")
print("===================   XXXXXXXXXXXXXXXXXXXXXXXXXXXX   ======================")
print("===================   XXXXXXXXXXXXXXXXXXXXXXXXXXXX   ======================")
print("===================   XXXXXXXXXXXXXXXXXXXXXXXXXXXX   ======================")
print("===================   XXXXXXXXXXXXXXXXXXXXXXXXXXXX   ======================")
print("===================   XXXXXXXXXXXXXXXXXXXXXXXXXXXX   ======================")
print("===================   XXXXXXXXXXXXXXXXXXXXXXXXXXXX   ======================")
print("===================   XXXXXXXXXXXXXXXXXXXXXXXXXXXX   ======================")
print("===================   XXXXXXXXXXXXXXXXXXXXXXXXXXXX   ======================")
print("===================   XXXXXXXXXXXXXXXXXXXXXXXXXXXX   ======================")
print()